### ISSUE TITLE
suggestions for README regarding personal privacy

### ISSUE THREAD

**Issue by gmcharlt** [code4lib/code4lib-map#5]
I suggest adding a guideline to the effect that one may add information regarding themselves or their institution, but that one should not add information regarding other people without their express permission. I also suggest adding a reminder to the effect that the history of changes to the data file is retained indefinitely and that there may be limited tools available for removing unwanted entries in a permanent fashion.

**Comment by kaitlinnewson** [comment]
Added! Thanks for pointing this out.
